android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId 'c83c5ac6-902b-4f26-94e7-4a3fc2746f5d'
            beaconUrl 'https://bf87797vgl.bf.dynatrace.com/mbeacon'
          }
          userOptIn true
          agentBehavior.startupLoadBalancing true
          agentBehavior.startupWithGrailEnabled true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>c83c5ac6-902b-4f26-94e7-4a3fc2746f5d</string>
    <key>DTXBeaconURL</key>
    <string>https://bf87797vgl.bf.dynatrace.com/mbeacon</string>
    <key>DTXUserOptIn</key>
    <true/>
    <key>DTXStartupLoadBalancing</key>
    <true/>
    <key>DTXStartupWithGrailEnabled</key>
    <true/>"
