name: recetasperuanas
description: "App de recetas de cocina"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  go_router: ^14.2.0
  logging: ^1.2.0
  sqflite: ^2.4.2
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  dio: ^5.8.0
  meta: ^1.16.0
  json_annotation: ^4.9.0
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  path: ^1.9.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_custom_tabs: ^2.4.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0

dev_dependencies:
  mockito: ^5.4.5
  test: ^1.25.15
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  very_good_analysis: ^5.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/logoOutName.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - lib/l10n/
    - assets/img/
    - assets/json/
